<div style="float:right; padding-top: 15px; padding-right: 15px">
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="250">
        </a>
    </div>
</div>

# data aggregation (with pandas)

## 1. introduction

* groupby is one of the most interesting methods of pandas df
* it is not easy to understand groupby objects at first sight, so repeated practice is very important here

## 2. data loading

Famous dataset of classic vehicles...

In [1]:
import pandas as pd
import numpy as np

Load `.csv` inside zip file...

In [2]:
from zipfile import ZipFile

z = ZipFile('./data/vehicles.zip')

z.infolist()

[<ZipInfo filename='vehicles/' filemode='drwxr-xr-x' external_attr=0x4000>,
 <ZipInfo filename='vehicles/.DS_Store' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=6148 compress_size=178>,
 <ZipInfo filename='__MACOSX/' filemode='drwxrwxr-x' external_attr=0x4000>,
 <ZipInfo filename='__MACOSX/vehicles/' filemode='drwxrwxr-x' external_attr=0x4000>,
 <ZipInfo filename='__MACOSX/vehicles/._.DS_Store' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=120 compress_size=53>,
 <ZipInfo filename='vehicles/vehicles_tab.txt' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=4959721 compress_size=300366>,
 <ZipInfo filename='vehicles/vehicles_pipe.txt' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=4959721 compress_size=300359>,
 <ZipInfo filename='vehicles/vehicles.json' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=13100011 compress_size=413028>,
 <ZipInfo filename='vehicles/vehicles.xlsx' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=2567387 compress_size=2510429>,
 <ZipInfo filename='vehicles/vehicles_messy.csv' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=15883588 compress_size=1392017>,
 <ZipInfo filename='vehicles/vehicles.csv' compress_type=deflate filemode='-rw-r--r--' external_attr=0x4000 file_size=4961209 compress_size=300449>]

In [3]:
vehicles = pd.read_csv(z.open('vehicles/vehicles.csv'))

In [4]:
vehicles.head().T

,0,1,2,3,4
Make,AM General,AM General,AM General,AM General,ASC Incorporated
Model,DJ Po Vehicle 2WD,FJ8c Post Office,Post Office DJ5 2WD,Post Office DJ8 2WD,GNX
Year,1984,1984,1985,1985,1987
Engine Displacement,2.5,4.2,2.5,4.2,3.8
Cylinders,4,6,4,6,6
Transmission,Automatic 3-spd,Automatic 3-spd,Automatic 3-spd,Automatic 3-spd,Automatic 4-spd
Drivetrain,2-Wheel Drive,2-Wheel Drive,Rear-Wheel Drive,Rear-Wheel Drive,Rear-Wheel Drive
Vehicle Class,Special Purpose Vehicle 2WD,Special Purpose Vehicle 2WD,Special Purpose Vehicle 2WD,Special Purpose Vehicle 2WD,Midsize Cars
Fuel Type,Regular,Regular,Regular,Regular,Premium
Fuel Barrels/Year,19.3888,25.3546,20.6006,25.3546,20.6006
City MPG,18,13,16,13,14
Highway MPG,17,13,17,13,21
Combined MPG,17,13,16,13,16
CO2 Emission Grams/Mile,522.765,683.615,555.438,683.615,555.438
Fuel Cost/Year,1950,2550,2100,2550,2550

In [5]:
vehicles.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 16.8 MB

In [6]:
vehicles.describe(include='all')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952,35952,35952.00000,35952.000000,35952.000000,35952,35952,35952,35952,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
unique,127,3608,NaN,NaN,NaN,45,8,34,13,NaN,NaN,NaN,NaN,NaN,NaN
top,Chevrolet,F150 Pickup 2WD,NaN,NaN,NaN,Automatic 4-spd,Front-Wheel Drive,Compact Cars,Regular,NaN,NaN,NaN,NaN,NaN,NaN
freq,3643,197,NaN,NaN,NaN,10585,13044,5185,23587,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2000.71640,3.338493,5.765076,NaN,NaN,NaN,NaN,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,NaN,NaN,10.08529,1.359395,1.755268,NaN,NaN,NaN,NaN,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,NaN,NaN,1984.00000,0.600000,2.000000,NaN,NaN,NaN,NaN,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,NaN,NaN,1991.00000,2.200000,4.000000,NaN,NaN,NaN,NaN,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,NaN,NaN,2001.00000,3.000000,6.000000,NaN,NaN,NaN,NaN,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,NaN,NaN,2010.00000,4.300000,6.000000,NaN,NaN,NaN,NaN,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,NaN,NaN,2017.00000,8.400000,16.000000,NaN,NaN,NaN,NaN,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

In [7]:
vehicles.describe(include='all')

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952,35952,35952.00000,35952.000000,35952.000000,35952,35952,35952,35952,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
unique,127,3608,NaN,NaN,NaN,45,8,34,13,NaN,NaN,NaN,NaN,NaN,NaN
top,Chevrolet,F150 Pickup 2WD,NaN,NaN,NaN,Automatic 4-spd,Front-Wheel Drive,Compact Cars,Regular,NaN,NaN,NaN,NaN,NaN,NaN
freq,3643,197,NaN,NaN,NaN,10585,13044,5185,23587,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2000.71640,3.338493,5.765076,NaN,NaN,NaN,NaN,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,NaN,NaN,10.08529,1.359395,1.755268,NaN,NaN,NaN,NaN,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,NaN,NaN,1984.00000,0.600000,2.000000,NaN,NaN,NaN,NaN,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,NaN,NaN,1991.00000,2.200000,4.000000,NaN,NaN,NaN,NaN,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,NaN,NaN,2001.00000,3.000000,6.000000,NaN,NaN,NaN,NaN,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,NaN,NaN,2010.00000,4.300000,6.000000,NaN,NaN,NaN,NaN,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,NaN,NaN,2017.00000,8.400000,16.000000,NaN,NaN,NaN,NaN,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

## 3. groupby object

In [8]:
vehicles.groupby('Transmission')

nothing to do with this object itself, let's explore it deeper...

## 4. aggregations

### single aggregation function, aggregation by a single column

In [9]:
vehicles.groupby('Transmission') \
['Highway MPG', 'City MPG', 'Combined MPG'].mean()

/home/david/miniconda3/envs/ml_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

                                  Highway MPG   City MPG  Combined MPG
Transmission
Auto (AV)                           40.000000  35.000000     37.000000
Auto (AV-S6)                        25.000000  22.000000     23.000000
Auto (AV-S8)                        22.000000  20.000000     21.000000
Auto(A1)                            37.000000  41.000000     39.000000
Auto(AM-S6)                         32.978261  24.315217     27.554348
Auto(AM-S7)                         25.300781  17.746094     20.425781
Auto(AM-S8)                         32.000000  23.666667     26.666667
Auto(AM-S9)                         22.000000  21.000000     21.000000
Auto(AM5)                           39.000000  33.666667     36.000000
Auto(AM6)                           31.345455  23.909091     26.736364
Auto(AM7)                           22.382166  16.248408     18.420382
Auto(AM8)                           28.600000  22.400000     24.600000
Auto(AV-S6)                         30.800000  25.944828     27.848276
Auto(AV-S7)                         33.746032  27.952381     30.206349
Auto(AV-S8)                         28.538462  22.846154     24.961538
Auto(L3)                            17.000000  14.000000     15.500000
Auto(L4)                            19.000000  13.500000     15.500000
Automatic (A1)                      31.666667  34.000000     32.666667
Automatic (A6)                      21.000000  14.000000     16.500000
Automatic (AM5)                     41.000000  33.000000     36.000000
Automatic (AM6)                     18.000000  13.000000     15.000000
Automatic (AV)                      30.000000  21.750000     24.750000
Automatic (AV-S6)                   27.777778  23.666667     25.222222
Automatic (S4)                      24.768559  18.074236     20.528384
Automatic (S5)                      24.205596  17.087591     19.698297
Automatic (S6)                      25.938807  18.337514     21.096921
Automatic (S7)                      23.605364  16.804598     19.195402
Automatic (S8)                      26.983333  18.450000     21.500000
Automatic (S9)                      28.307692  19.923077     23.038462
Automatic (variable gear ratios)    31.094815  27.460741     28.777778
Automatic 3-spd                     21.630343  17.449750     19.033500
Automatic 4-spd                     21.691639  15.944261     18.042607
Automatic 5-spd                     21.647167  15.445417     17.693229
Automatic 6-spd                     23.768156  16.720670     19.237430
Automatic 6spd                      34.000000  21.000000     26.000000
Automatic 7-spd                     24.413897  17.117825     19.746224
Automatic 8-spd                     24.448560  16.576132     19.279835
Automatic 9-spd                     28.366667  20.077778     23.200000
Manual 3-spd                        16.945946  14.229730     15.256757
Manual 4-spd                        21.042113  16.871363     18.462481
Manual 5 spd                        14.000000  14.000000     14.000000
Manual 5-spd                        25.664312  19.242327     21.634391
Manual 6-spd                        26.202229  18.306232     21.153941
Manual 7-spd                        26.205882  18.220588     21.117647
Manual(M7)                          22.333333  14.000000     17.000000

### aggregation by multiple columns, single aggregation function

In [10]:
vehicles.groupby(['Fuel Type', 'Cylinders']) \
    ['CO2 Emission Grams/Mile'].mean().sort_values(ascending=True)

Fuel Type                    Cylinders
Premium Gas or Electricity   2.0           39.000000
Regular Gas or Electricity   4.0           51.000000
Premium Gas or Electricity   4.0           96.000000
Regular Gas and Electricity  4.0          125.687500
Premium and Electricity      3.0          198.000000
                             4.0          206.333333
                             6.0          235.333333
Regular                      3.0          246.518217
Premium                      3.0          253.485043
CNG                          4.0          257.539637
Premium Gas or Electricity   6.0          259.333333
                             8.0          277.000000
Diesel                       4.0          330.909525
Gasoline or E85              4.0          359.073842
Premium or E85               4.0          368.142857
Regular                      4.0          381.906539
Gasoline or natural gas      4.0          383.464097
Premium                      4.0          389.573558
Midgrade                     6.0          406.800000
CNG                          6.0          417.030882
Premium or E85               6.0          423.276621
Diesel                       5.0          425.288362
                             6.0          435.797518
Premium                      5.0          436.029637
Gasoline or natural gas      6.0          437.000000
Regular                      5.0          452.069902
Gasoline or E85              6.0          454.282739
Premium                      6.0          454.941429
Premium and Electricity      8.0          463.000000
Premium                      2.0          486.635300
Regular                      6.0          506.475468
                             2.0          513.925689
Premium or E85               8.0          524.687500
Midgrade                     8.0          524.891046
Premium                      8.0          560.324585
CNG                          8.0          573.309895
Diesel                       8.0          589.949213
                             10.0         590.506536
Gasoline or E85              8.0          594.649022
Premium or E85               12.0         624.215035
Regular                      8.0          636.099229
Premium                      10.0         646.760443
Gasoline or propane          8.0          666.525000
Premium                      12.0         698.033195
Regular                      12.0         712.338223
Gasoline or natural gas      8.0          768.310391
Regular                      10.0         776.748106
Premium                      16.0         873.062500
Name: CO2 Emission Grams/Mile, dtype: float64

### aggregation using agg method

In [11]:
vehicles.groupby('Fuel Type')['Combined MPG', 'Highway MPG'].agg(['min', 'max', 'mean', 'median', 'std'])

/home/david/miniconda3/envs/ml_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

                            Combined MPG                                  \
                                     min max       mean median       std
Fuel Type
CNG                                    9  31  18.133333   14.5  7.436663
Diesel                                14  40  23.488474   21.0  7.054702
Gasoline or E85                       11  33  17.572385   17.0  3.822538
Gasoline or natural gas               10  24  15.350000   12.0  5.343712
Gasoline or propane                   12  15  13.500000   13.5  1.603567
Midgrade                              15  24  17.378378   17.0  1.848381
Premium                                7  45  19.343816   19.0  4.097972
Premium Gas or Electricity            20  39  31.647059   33.0  7.158397
Premium and Electricity               17  39  26.300000   25.5  5.141165
Premium or E85                        13  27  20.090909   20.0  3.676502
Regular                                8  56  20.144698   20.0  5.317500
Regular Gas and Electricity           38  50  41.937500   38.5  5.246824
Regular Gas or Electricity            42  42  42.000000   42.0  0.000000

                            Highway MPG
                                    min max       mean median       std
Fuel Type
CNG                                  11  38  22.016667   18.5  9.058177
Diesel                               16  46  27.466520   24.0  8.660046
Gasoline or E85                      14  40  21.613389   20.0  5.007313
Gasoline or natural gas              11  30  18.700000   15.0  6.522027
Gasoline or propane                  15  18  16.500000   16.5  1.603567
Midgrade                             19  29  22.364865   22.0  2.373220
Premium                              10  48  23.855861   24.0  4.728452
Premium Gas or Electricity           21  40  33.176471   35.0  6.930326
Premium and Electricity              20  41  28.900000   29.0  5.240530
Premium or E85                       18  33  24.909091   25.0  4.006245
Regular                               9  61  23.854623   24.0  6.147280
Regular Gas and Electricity          36  49  40.750000   38.0  5.662744
Regular Gas or Electricity           42  42  42.000000   42.0  0.000000

### specific aggregation for columns

In [12]:
vehicles.groupby('Fuel Type').agg(min_mpg_combined=('Combined MPG', 'min'),
                                  max_mpg_highway=('Highway MPG', 'max'))

                             min_mpg_combined  max_mpg_highway
Fuel Type
CNG                                         9               38
Diesel                                     14               46
Gasoline or E85                            11               40
Gasoline or natural gas                    10               30
Gasoline or propane                        12               18
Midgrade                                   15               29
Premium                                     7               48
Premium Gas or Electricity                 20               40
Premium and Electricity                    17               41
Premium or E85                             13               33
Regular                                     8               61
Regular Gas and Electricity                38               49
Regular Gas or Electricity                 42               42

### custom aggregations

In [13]:
from scipy import stats

In [14]:
stats.mode([1, 2, 3, 3, 4])

ModeResult(mode=array([3]), count=array([2]))

In [15]:
def agg_custom_function(col):
    return np.max(col) / np.min(col)
    # return stats.mode(col)[0]

In [16]:
vehicles.groupby('Transmission')["Combined MPG"].agg(agg_custom_function)

Transmission
Auto (AV)                           1.000000
Auto (AV-S6)                        1.000000
Auto (AV-S8)                        1.000000
Auto(A1)                            1.000000
Auto(AM-S6)                         2.437500
Auto(AM-S7)                         4.500000
Auto(AM-S8)                         1.160000
Auto(AM-S9)                         1.000000
Auto(AM5)                           1.000000
Auto(AM6)                           3.818182
Auto(AM7)                           3.181818
Auto(AM8)                           1.318182
Auto(AV-S6)                         2.000000
Auto(AV-S7)                         2.000000
Auto(AV-S8)                         1.550000
Auto(L3)                            1.066667
Auto(L4)                            1.066667
Automatic (A1)                      1.950000
Automatic (A6)                      2.000000
Automatic (AM5)                     1.000000
Automatic (AM6)                     1.000000
Automatic (AV)                      1.333333
Automatic (AV-S6)                   1.363636
Automatic (S4)                      1.625000
Automatic (S5)                      3.000000
Automatic (S6)                      4.625000
Automatic (S7)                      3.100000
Automatic (S8)                      2.846154
Automatic (S9)                      1.250000
Automatic (variable gear ratios)    2.947368
Automatic 3-spd                     4.500000
Automatic 4-spd                     3.666667
Automatic 5-spd                     3.000000
Automatic 6-spd                     3.272727
Automatic 6spd                      1.000000
Automatic 7-spd                     2.750000
Automatic 8-spd                     1.800000
Automatic 9-spd                     1.750000
Manual 3-spd                        1.545455
Manual 4-spd                        4.000000
Manual 5 spd                        1.000000
Manual 5-spd                        7.571429
Manual 6-spd                        4.500000
Manual 7-spd                        2.300000
Manual(M7)                          1.750000
Name: Combined MPG, dtype: float64

<div style="padding-top: 25px; float: right">
    <div>    
        <i>&nbsp;&nbsp;© Copyright by</i>
    </div>
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="125">
        </a>
    </div>
</div>